@startuml

title Diagramme de séquence de la solution 1 de réduction de couleurs

activate Main

Main -> Solution_v1: reductionCouleurs(image, nbCouleurs)
activate Solution_v1

Solution_v1 -> Solution_v1: rassemblerCouleurs(image)
activate Solution
Solution <-- Solution_v1: calculDistance(origine, destination)
Solution --> Solution_v1: distance
deactivate Solution

loop Pour chaque pixel de l'image
    Solution_v1 -> Solution: remplacerCouleurs(image, couleursRepresentatives)
    activate Solution
    Solution <-- Solution_v1: imageReduite
    deactivate Solution
end

Solution_v1 --> Main: imageReduite
deactivate Solution_v1
Main <-- imageReduite

@enduml